### ISSUE TITLE
react-hook-form useFieldArray throws error with uix v1.3.0 upwards

### ISSUE THREAD

**Issue by belafonte** [pitch-io/uix#250]
I updated uix today, first to 1.3.0 then to 1.4.4 from 1.0.1 and now iam experiencing an issue with react-hook-form

the useFieldArray seems not to work anymore and throws an error:

`Uncaught TypeError: Cannot read properties of null (reading '_getFieldArray')
    at Object.useFieldArray (libs.js:61432:73)
    at f__29912__auto__ (leihs.inventory.client.routes.models.crud.components.accessories_list.js:44:56)
    at leihs.inventory.client.routes.models.crud.components.accessories-list/main [as main] (leihs.inventory.client.routes.models.crud.components.accessories_list.js:64:8)`

`libs.js:69247 Error handled by React Router default ErrorBoundary: TypeError: Cannot read properties of null (reading '_getFieldArray')`

Something like this should trigger the error:

`{:keys [fields append remove move]} (js->clj  (hook-form/useFieldArray
                                                                     (clj->js {:control control
                                                                                    :name "accessories"})) {:keywordize-keys true})`

This was working with uix 1.0.1

We are still on react@18.2.0 
Might this be the issue?

**Comment by roman01la** [comment]
no response, closing for now
